language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

install:
  - composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-clover tests/coverage-clover.xml

after_script:
  - '[ "5.5" = "$(phpenv version-name)" ] && composer require satooshi/php-coveralls:dev-master && vendor/bin/coveralls -v'

